config/routes.rb
Rails.application.routes.draw do

  resources :novels
  resources :characters
  resources :channels

  resources :posts do
    resources :comments
  end

  resources :discussions do
    resources :replies
  end

  root "pages#home"
  get '/about', to: 'pages#about'
  get '/character', to: 'characters#index'
  get "news" => 'posts#index'
  # get '/novel', to: 'pages#novel'
  get '/forum', to: 'discussions#index'
  get '/novel', to: 'novels#index'



  devise_for :users, controllers: { registrations: 'registrations' }


end

app/models/discussion.rb
class Discussion < ActiveRecord::Base

    belongs_to :channel
    belongs_to :user
    has_many :replies, dependent: :destroy

    validates :title, presence: { :message => "El titulo no puede estar vacio" }, length: { minimum: 5, :message => "El Título es muy corto (El minimo es 5 carácteres)"  }
    validates :content, presence: { :message => "El Contenido no puede estar vacio" }
    validates :channel, presence: { :message => "El Tema no puede estar vacio" }
    validates :title, :uniqueness => { :message => "El titulo de esto post ya ha sido tomado" }
    validate :channel_existing
    resourcify

    extend FriendlyId 
    friendly_id :title, use: [:slugged, :finders]

    def should_generate_new_friendly_id?
        title_changed?
    end

    private
    def channel_existing
        errors.add(:channel_id, :missing) if channel.blank?
    end
end

app/controllers/discussions_controller.rb
class DiscussionsController < ApplicationController
  before_action :set_discussion, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, except: [:index, :show]
  before_action :find_channels, only: [:index, :show, :new, :edit]
  before_action :discussion_owner, only: [:edit, :update, :destroy]

  # GET /discussions
  # GET /discussions.json
  def index
    @discussions = Discussion.all.order('created_at desc')
  end

  # GET /discussions/1
  # GET /discussions/1.json
  def show
    @discussions = Discussion.all.order('created_at desc')
  end

  # GET /discussions/new
  def new
    @discussion = current_user.discussions.build
  end

  # GET /discussions/1/edit
  def edit
  end

  # POST /discussions
  # POST /discussions.json
  def create
    @discussion = current_user.discussions.build(discussion_params)

    respond_to do |format|
      if @discussion.save
        format.html { redirect_to @discussion, notice: 'La Discusión ha sido creada exitosamente!' }
        format.json { render :show, status: :created, location: @discussion }
      else
        format.html { render :new }
        format.json { render json: @discussion.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /discussions/1
  # PATCH/PUT /discussions/1.json
  def update
    respond_to do |format|
      if @discussion.update(discussion_params)
        format.html { redirect_to @discussion, notice: 'La Discusión ha sido editada exitosamente!' }
        format.json { render :show, status: :ok, location: @discussion }
      else
        format.html { render :edit }
        format.json { render json: @discussion.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /discussions/1
  # DELETE /discussions/1.json
  def destroy
    @discussion.destroy
    respond_to do |format|
      format.html { redirect_to discussions_url, notice: 'La Discusión ha sido borrada exitosamente!' }
      format.json { head :no_content }
    end
  end

  def discussion_owner
    unless @discussion.user_id == current_user.id || current_user.has_role?(:admin)
     flash[:notice] = 'Acceso denegado porque no eres el dueño de esta discusión'
     redirect_to discussions_path
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_discussion
      @discussion = Discussion.find(params[:id])
    end

    def find_channels
      @channels = Channel.all.order('created_at desc')
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def discussion_params
      params.require(:discussion).permit(:title, :content, :channel_id)
    end
end

app/helpers/discussions_helper.rb
module DiscussionsHelper

    def discussion_author(discussion)
        user_signed_in? && current_user.id == discussion.user_id
    end
    
    def reply_author(reply)
        user_signed_in? && current_user.id == reply.user_id
    end

end

app/views/discussions/_form.html.erb
<%= simple_form_for(@discussion) do |f| %>
       <% if @discussion.errors.any? %>
        <div id="errors">
            <h2> 
                <%= pluralize(@discussion.errors.count, "error") %> 
                Prevented this post from saving
            </h2>
            <ul>
                <% @discussion.errors.full_messages.each do |msg| %>
                    <li> <%= msg %> </li>
                <% end %>
            </ul>
        </div>
      <% end %>

  <div class="field">
    <div class="control">
      <%= f.input :title, required: true, input_html: { class: 'input' }, wrapper: false, label_html: { class: "label" }, :label => "Titulo" %>
    </div>
  </div>

  <div class="field">
    <div class="control">
      <%= f.input :content, required: true, input_html: { class: 'textarea' }, wrapper: false, label_html: { class: "label" }, :label => "Contenido" %>
    </div>
  </div>

  <div class="field">
    <label class="label">Tema</label>
    <div class="control has-icons-left">
      <span class="select">
        <%= f.input_field :channel_id, collection:@channels.map { |c| [c.channel, c.id] }, prompt: "Seleccionar tema" %>
      </span>
      <span class="icon is-small is-left">
        <i class="fa fa-tag"></i>
      </span>
    </div>
  </div>

  <div class="field">
    <div class="control">
      <%= f.button :submit, value: "#{f.object.new_record? ? 'Crear Discusión' : 'Actualizar Discusión'}", class:"button is-info" %>
    </div>
  </div>

<% end %>

app/views/discussions/_sidebar.html.erb
<div class="column is-3 is-offset-1">
    <h3 class="title is-3 has-text-grey-dark">Temas</h3>

    <ul class="list">
        <% @channels.each do |t| %>
            <li><%= link_to t.channel, t%></li>
        <% end %>
    </ul>
    
    <br>

    <% if has_role?(:admin) %>
        <%= link_to_focus_button_info 'Nuevo Tema', new_channel_path, class: '' %>
        <%= link_to_focus_button_info 'Editar Temas', channels_path, class: '' %>
    <% end %>
</div>

app/views/discussions/edit.html.erb
<div class="box">
    <h1>Editar Discusión</h1>
        <%= render 'form' %>
        <%= link_to 'Show', @discussion %> |
        <%= link_to 'Back', discussions_path %>
      <p class="has-text-center">Lo sentimos! No tienes acceso a esta página.</p>
</div>

app/views/discussions/index.html.erb
<div class="columns post_wrapper">
  <%= render 'shared/discussions' %>
  <%= render 'sidebar' %>
</div>

app/views/discussions/new.html.erb
<div class="post_wrapper">
    <h1 class="title is-size-3">Nueva discusión</h1>
        <%= render 'form' %><br>
        <%= link_to 'Atrás', discussions_path %>
</div>

app/views/discussions/show.html.erb
<div class="columns post_wrapper">
  <div class="column is-8">
    <div class="box">

    <h1 id="focus" class="title is-2 has-text-grey-dark discussion-title"><%= @discussion.title %></h1>
    <h3 class="subtitle is-5 has-text-grey-light">por 
      <% if @discussion.user.has_role?(:admin) %>
        <%= @discussion.user.username %> 
        <strong class="subtitle is-5 has-text-warning shadow ml10 mr10">(Administrador)</strong>
      <% else %>
        <%= @discussion.user.username %>
      <% end %> 
      en <%= link_to @discussion.channel.channel, @discussion.channel %>
    </h3>
    <div class="level">
      <div class="level-left"></div>
      <div class="level-right">
        <% if discussion_author(@discussion) %>
        <div class="buttons">
          <a class="level-item">
            <%= link_to edit_discussion_path(@discussion), :title => "Editar" do %>
              <span class="icon is-large"><i class="fa fa-pencil fas fa-2x"></i></span>
            <% end %>
          </a>
          <a class="level-item">
            <%= link_to discussion_path(@discussion), method: :delete, data: { confirm: "¿Estas seguro de querer borrar esta Discusión?" }, :title => "Borrar" do %>
              <span class="icon is-large"><i class="fa fa-trash-o fas fa-2x	"></i></span>
            <% end %>
          </a>
        </div>
       <% end %>
      </div>
    </div>
    <div class="content"><%= markdown(@discussion.content) %></div>
  </div>
    <h2 class="subtitle is-4 has-text-grey"><%= @discussion.replies.count %> Respuestas</h2>

    <div id="discussion-replies">
      <%= render @discussion.replies %>
    </div>

    <hr />

    <h3 class="subtitle is-3 has-text-grey">Deja una respuesta</h3>
    <% if user_signed_in? %>
      <%= render 'replies/form' %>
    <% else %>
      <p>Para responder necesitas <%= link_to 'Iniciar sesión', new_user_session_path %>. No tienes cuenta?
      <%= link_to 'Registrate', new_user_registration_path %> para una.</p>
    <% end %>

  </div>

  <%= render 'sidebar' %>

</div>