config/routes.rb
Rails.application.routes.draw do

  resources :novels
  resources :characters
  resources :channels

  resources :posts do
    resources :comments
  end

  resources :discussions do
    resources :replies
  end

  root "pages#home"
  get '/about', to: 'pages#about'
  get '/character', to: 'characters#index'
  get "news" => 'posts#index'
  # get '/novel', to: 'pages#novel'
  get '/forum', to: 'discussions#index'
  get '/novel', to: 'novels#index'



  devise_for :users, controllers: { registrations: 'registrations' }


end

app/models/character.rb
class Character < ActiveRecord::Base
    belongs_to :user

    validates_uniqueness_of :name

end

app/controllers/characters_controller.rb
class CharactersController < ApplicationController
  before_action :find_character, only: [:show, :edit, :update, :destroy]

  def index
    @characters = Character.all
  end

  def new
    @character = current_user.characters.build
  end

  def create
    @character = current_user.characters.build(character_params)
      if @character.save
      redirect_to @character #redirect_to hace un llamado http completo
      else 
          render 'new' #la diferencia entre render y redirect es que con render si por error no guarda el post, no pierdo la información que he escrito.
      end 
  end
  
  def show
  end

  def edit
  end

  def update
      if @character.update(params[:character].permit(:name))
          redirect_to @character
      else
          render 'edit'
      end
  end

  def destroy
      @character.destroy
      redirect_to root_path
  end

  private

    def character_params
      params.require(:character).permit(:name)
    end

    def find_character
      @character = Character.find(params[:id])
    end

end

app/helpers/characters_helper.rb
module CharactersHelper
end

app/views/characters/_form.html.erb
<%= simple_form_for(@character) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs">
    <%= f.input :name %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/characters/edit.html.erb
<h1>Editing Character</h1>

<%= render 'form' %>

<%= link_to 'Show', @character %> |
<%= link_to 'Back', characters_path %>

app/views/characters/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Characters</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @characters.each do |character| %>
      <tr>
        <td><%= character.name %></td>
        <td><%= link_to 'Show', character %></td>
        <td><%= link_to 'Edit', edit_character_path(character) %></td>
        <td><%= link_to 'Destroy', character, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Character', new_character_path %>

app/views/characters/new.html.erb
<h1>New Character</h1>

<%= render 'form' %>

<%= link_to 'Back', characters_path %>

app/views/characters/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @character.name %>
</p>

<%= link_to 'Edit', edit_character_path(@character) %> |
<%= link_to 'Back', characters_path %>