config/routes.rb
Rails.application.routes.draw do

  resources :novels
  resources :characters
  resources :channels

  resources :posts do
    resources :comments
  end

  resources :discussions do
    resources :replies
  end

  root "pages#home"
  get '/about', to: 'pages#about'
  get '/character', to: 'characters#index'
  get "news" => 'posts#index'
  # get '/novel', to: 'pages#novel'
  get '/forum', to: 'discussions#index'
  get '/novel', to: 'novels#index'



  devise_for :users, controllers: { registrations: 'registrations' }


end

app/views/layouts/_header.html.erb
<div class="mb10">
    <% if current_page?(root_path) %>
<%= image_tag "header.jpeg", :class => "img-responsive" %>
    <% elsif current_page?(about_path) %>
<%= image_tag "header1.jpeg", :class => "img-responsive" %>
    <% elsif current_page?(news_path) %>
<%= image_tag "header.jpeg", :class => "img-responsive" %>
    <% elsif current_page?(discussions_path) %>
<%= image_tag "header1.jpeg", :class => "img-responsive" %>
<!--    < % elsif current_page?(novel_path) %>
< % = image_tag "header1.jpeg", :class => "img-responsive" %> -->
    <% else %>
<%= image_tag "header.jpeg", :class => "img-responsive" %>
    <% end %>
</div>


    <% flash.each do |name, msg| %>
        <section class="flash-message hero is-primary">
            <div class="hero-body">
                <div class="container">
                    <h1 class="title">
                        Notificación:
                    </h1>
                    <h2 class="subtitle is-2">
                        <%= content_tag(:div, msg, class: "alert")  %>
                    </h2>
                </div>
            </div>
        </section>
    <% end %>      
 
 <br>
  <div class="columns">
        <div class="column has-text-centered is-3">
            <div class="logo">
                <%= link_to root_path do %>
                    <%= image_tag "logo.png", class: 'logo', style: 'height:100%;width:80%;' %>
                <% end %>
            </div>
        </div>
        <div class="column">
            <%= image_tag "image_slider.jpg", class: 'img-responsive ' %>
            <a href="https://www.facebook.com/amesthy/?ref=br_rs" target="_blank">
                <div class="box has-text-centered facebook-btn">
                    Facebook
                </div>
            </a>
        </div>

        <div class="column">
        
            <% if !user_signed_in? %>
                    <div class="box">

                <%= form_for(resource, as: resource_name, url: session_path(resource_name)) do |f| %>
                <div class="field">
                    <%= f.label :email %><br />
                    <%= f.email_field :email, autofocus: true, autocomplete: "email" %>
                <br>
                </div>

                <div class="field">
                    <%= f.label :password %><br />
                    <%= f.password_field :password, autocomplete: "off" %>
                <br>
                </div>

                <br>
                <div class="actions">
                    <%= f.submit "Iniciar sesión" %>
                    <%= link_to "Registrarte", new_user_registration_path, class: 'button2' %>

                </div>
                <% end %>
                </div>
                <br>
            <% end %>
            <% if user_signed_in? %>
                <div class="box">
                    <h1 class="has-text-centered">Bienvenida</h1>
                    Conectado como: <%= current_user.username %><br>
                    Amei: <%= current_user.coin %><br>
                    <% if current_user.has_role?(:admin || :moderator) %>
                        Rol: <strong><%= current_user.roles_name.join("','").capitalize %></strong><br>            
                    <% end %>
                    Chico favorito:  <%= current_user.character_name %> | <a onclick="myFunction()">cambiar</a><br>
                    <div id="myDIV">
                        <%= simple_form_for(resource, as: resource_name, url: registration_path(resource_name), html: { method: :put }) do |f| %>
                            <h2 class="title is-2 is-danger">
                                <%= f.error_notification %>
                            </h2>

                            <div class="field">
                                <label class="label">Chico favorito:</label>
                                <div class="control has-icons-left">
                                    <span class="select">
                                        <%= f.select :character_name, Character.where("name <> ?", current_user.character_name).pluck(:name, :name), :prompt => current_user.character_name %> 
                                    </span>

                                    <span class="icon is-small is-left">
                                        <i class="fa fa-tag"></i>
                                    </span>
                                </div>
                            </div>

                    
                            <div class="field">
                                <div class="control">
                                <%= f.input :current_password, hint: "Necesitamos su contraseña para confirmar los cambios", required: true, input_html: { class: "input"}, wrapper: false, label_html: { class: "label" }, label: 'Contraseña' %>
                                </div>
                            </div>

                            
                            <%= f.button :submit, "Actualizar", class:"button is-info" %>
                            <script>
                                function myFunction() {
                                    var x = document.getElementById("myDIV");
                                    if (x.style.display === "none") {
                                        x.style.display = "block";
                                    } else {
                                        x.style.display = "none";
                                    }
                                }
                            </script>

                        <% end %>
                    </div><br>

                    <div class="buttons is-centered">
                        <%= link_to_focus_button "Editar cuenta", edit_user_registration_path, class:'' %>
                        <%= link_to "Salir", destroy_user_session_path, method: :delete, :class => 'button is-primary' %>
                    </div>
                </div>
            <% end %>
        </div>
    </div>



<div id="menu_root">
    <nav class="navbar is-primary">
        <div class="navbar-brand">
            <a class="navbar-item is-hidden-desktop">
                Menu
            </a>
            <div class="navbar-burger burger" data-target="navbarExampleTransparentExample">
            <span></span>
            <span></span>
            <span></span>
            </div>
        </div>

        <div id="navbarExampleTransparentExample" class="navbar-menu">
                <div class="navbar-start">
                    
                    <a><%= link_to "Inicio", root_path, :class => "navbar-item  mr50" %></a>
                    <a><%= link_to_focus_navbar "Blog", news_path, :class => "" %></a>
                    <a><%= link_to_focus_navbar "Novelas", novels_path, :class => "" %></a>
                   <!-- <a>< % = link_to "Novelas Visuales", novel_path, :class => "navbar-item  mr50" %></a>-->
                    <a><%= link_to_focus_navbar "Galería", root_path, :class => "" %></a>
                    <a><%= link_to_focus_navbar "Tienda", root_path, :class => "" %></a>
                    <a href="#focus"><%= link_to_focus_navbar_item "Foro", discussions_path, class: ''%></a>
                </div>
        </div>
    </nav>
</div>

app/views/layouts/_news.html.erb
<div class="box">
    <h1 class="title is-3  has-text-grey-dark has-text-centered">Noticias</h1>
        <% @posts.each do |post| %>
            <div class="">
                <!--<%= image_tag  "avatar.png" %>-->
                <h2 class="title is-5 has-text-grey-dark "> <%= link_to post.title, post %> </h2>
                <p class="subtitle is-6 has-text-grey-light"> <%= post.created_at.strftime("%B, %d, %Y")%> </p>
            </div>
            <div class="bb-not-last pv10"></div>
        <% end %>

        <%= will_paginate @posts, previous_label: "Anterior", next_label: "Siguiente", :page_links => true, renderer: BulmaPagination::Rails, class: 'is-centered' %>
</div>

app/views/layouts/_sidebar.html.erb
<div class="">

 <div id="menu">
    <div class="logo">
        <%= link_to root_path do %>
            <%= image_tag "logo.png", :class=> "img-responsive img-logo" %>
        <% end %>
    </div>
    <ul>
        <li class="category">Website</li>
        <li> <%= link_to "Inicio", root_path, :class => "tags" %></li>
        <li> <%= link_to "Blog", news_path, :class => "tags" %></li>
        <li> <%= link_to "Novelas", novel_path, :class => "tags" %></li>
        <li> <%= link_to "Tienda", root_path, :class => "tags" %></li>             
    </ul>
    <ul>
        <li class="category">Social</li>
        <li> <%= link_to "Foro", discussions_path, :class => "tags" %></li>
        <li> <%= link_to "About", about_path, :class => "tags" %></li>
        <li> <%= link_to "Facebook", root_path, :class => "tags" %></li>
        <li> <%= link_to "Instagram", root_path, :class => "tags" %></li>
    </ul>
    <!--<div class="espaciado"></div>-->
</div>


</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>WebVisualNovelSystem</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <%= stylesheet_link_tag 'application', 'https://fonts.googleapis.com/css?family=Dancing+Script|Raleway' %>

</head>
<body>


<!--<p class="notice"><%= notice %></p>
<p class="alert"><%= alert %></p>-->

  

  <div class="wrapper">
    <header class="main-head">
      <div id="main_content">
        <%= render 'layouts/header' %>
      </div>
    </header>
    <article class="content">
      <div id="focus" class="">
        <%= yield %>
      </div>
    </article> 
    <footer class="main-footer">
      <div class="footer">
        Footer
      </div>
    </footer>
  </div>

</body>
</html>